server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=productdb;trustServerCertificate=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  application:
    name: PRODUCT-SERVICE
  config:
    import: optional:configserver:http://localhost:9296
