server:
  port: 9296

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pthelong2000/app-config
          clone-on-start: true
  application:
    name: CONFIG-SERVER